routes/Students.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from services.Students import studentsService
from services.TypeId import typeIdService
from services.Documents import documentService
from services.Administrativo import AdministrativeService

Estudiante = Blueprint("Estudiante", __name__)


@Estudiante.route("/home_student")
def home_Student():
    if "code" in session:
        if session["type_of_user"] == 1:
            code = session["code"]
            student = studentsService().get_student(code)
            documents = documentService.get_document_cod_student(code)
            if documents == []:
                document = []
            else:
                document = documents[0]
            return render_template(
                "home_student.html", student=student, document=document
            )
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))



@Estudiante.route("/students")
def crud_Student():
    if "code" in session:
        if session["type_of_user"] == 2:
            code = session["code"]
            administrative = AdministrativeService().get_administrative(code)
            typeids = typeIdService().get_typeIds()
            students = studentsService().get_students()
            return render_template("crud_student.html", typeids=typeids, students=students,administrative=administrative)
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))


@Estudiante.route("/new_student", methods=["POST"])
def new_Student():
    if "code" in session:
        if session["type_of_user"] == 2:
            codigo_Student = request.form["codigo_Student"]
            name = request.form["name"]
            lastname = request.form["lastname"]
            id_typeid = int(request.form["id_typeid"])
            IDNumber = request.form["IDNumber"]

            #consultamos si ese estudiante ya existe
            students = studentsService().get_student(codigo_Student)
            if students:
                flash("Este estudiante ya existe")
                return redirect(url_for("Estudiante.crud_Student"))
            else:
                studentsService.create_student(
                    codigo_Student, name, lastname, id_typeid, IDNumber
                )
            return redirect(url_for("Estudiante.crud_Student"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))


@Estudiante.route("/update_student/<id>" , methods=["GET", "POST"])
def update_Student(id):
    if "code" in session:
        if session["type_of_user"] == 2:
            idviejo = id
            studennt = studentsService().get_student(idviejo)
            code = session["code"]
            administrative = AdministrativeService().get_administrative(code)
            if request.method == "GET":
                typeids = typeIdService().get_typeIds()
                return render_template("update_student.html", student=studennt, typeids=typeids,administrative=administrative)

            if request.method == "POST":
                name = request.form["name"]
                lastname = request.form["lastname"]
                id_typeid = int(request.form["id_typeid"])
                IDNumber = request.form["IDNumber"]
                studentsService.update_student(
                idviejo, name, lastname, id_typeid, IDNumber
            )
            return redirect(url_for("Estudiante.crud_Student"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))


@Estudiante.route("/delete_student/<id>")
def delete_Student(id):
    if "code" in session:
        if session["type_of_user"] == 2:
            studentsService.delete_student(id)
            return redirect(url_for("Estudiante.crud_Student"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))

templates/crud_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/crud_students.css">
    <link rel="stylesheet" href="../static/css/menssages.css">
    <link rel="stylesheet" href="../static/css/sidebar.css">
    <title>Estudiantes</title>
</head>
<body id="body">
    {% include './partial/sidebar.html' %}
    <div class="container crud-table" ng-app="myApp" ng-controller="namesCtrl">
        <div class="clearfix">
            <div class="form-inline pull-left"><button class="btn btn-success" id="add" onclick="add()"><span class="glyphicon glyphicon-plus"> </span>Añadir Estudiantes</button></div>
            <div class="form-inline pull-right"><p>Buscar:</p><div class="form-group"><input class="form-control" type="text"  placeholder="Buscar"  id="inputSearch" onkeyup="search()"/></div>
            </div>
        </div>
        <table class="table table-striped" id="tablaStudent">
            <thead>
                <tr>
                    <th>Codigo Estudiantil</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Tipo de identificacion</th>
                    <th>Numero de identificacion</th>
                    <th><i class="fa-solid fa-user-pen" title="Inicio"></i></th>
                    <th><i class="fa-solid fa-trash-can" title="Inicio"></i></th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for student in students%}
                <tr>
                    <td>{{student.codigo_Student}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.lastname}}</td>
                    <td>{{student.TypeId.description}}</td>
                    <td>{{student.IDNumber}}</td>
                    <td><button class="btn btn-primary"><a href="{{url_for('Estudiante.update_Student',id=student.codigo_Student)}}">Editar</a></button></td>
                    <td><button class="btn btn-danger"><a href="{{ url_for('Estudiante.delete_Student',id=student.codigo_Student) }}">Eliminar</a></button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="crude-form__wrapper" id="container" style="display:none">
            <h3 id="ed" style="display:block">Editar Estudiante</h3>
            <h3 id="ad" style="display:block">Agregar Estudiante</h3>
            <form action="/new_student" autocomplete="off" method="POST" id="form" style="display:block">
                <div class="form-group"><label for="codigo_Student">Codigo Estudiantil</label><input class="form-control" id="codigo_Student" type="number" name="codigo_Student" ng-model="crudFormName" placeholder="Ingrese el codigo estudiantil" required="required" />
                </div>
                <div class="form-group"><label for="name">Nombre</label><input class="form-control" id="name" type="text" name="name" ng-model="crudFormCountry" placeholder="Ingrese el Nombre" required="required" />
                </div>
                <div class="form-group"><label for="lastname">Apellido</label><input class="form-control" id="lastname" type="text" name="lastname" ng-model="crudFormSalary" placeholder="Ingrese el Apellido" min="1" required="required" />
                </div>
                <div class="form-group">
                    <label for="id_typeid">Tipo de identificacion</label>
                    <select name="id_typeid" id="id_typeid" class="form-control">
                        {% for type in typeids %}
                        <option id="select" value="{{type.id}}">{{type.description}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group"><label for="IDNumber">Numero de identificacion</label><input class="form-control id_number" id="IDNumber" type="number" name="IDNumber" ng-model="crudFormEmail" placeholder="Ingrese el numero de identificacion" required="required" />
                    <button class="btn btn-primary" id="btn">
                    </button>
                    <button class="btn btn-primary" onclick="delet()"> Cancel</button>
            </form>
        </div>
    </div>
    {%include './partial/_message.html'%}
<script src="../static/javascript/crud_stuent.js"></script>
<script
src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
crossorigin="anonymous"
></script>
<script src="https://kit.fontawesome.com/79f542cb27.js" crossorigin="anonymous"></script>
<script src="../static/javascript/sidebar.js"></script>
</body>
</html>

templates/home_administrative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/home_adm.css">
    <link rel="stylesheet" href="../static/css/sidebar.css">
    <title>Home</title>
</head>
<body id="body">
    {% include './partial/sidebar.html' %}
    <div class="contenedor-principal">
        {% include './partial/main_home_adm.html' %}
    </div>
    <script src="../static/javascript/home_adm.js"></script>
    <script src="https://kit.fontawesome.com/79f542cb27.js" crossorigin="anonymous"></script>
    <script src="../static/javascript/sidebar.js"></script>
</body>
</html>

templates/home_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/home_student.css">
    <link rel="stylesheet" href="../static/css/footer.css">
    <link rel="stylesheet" href="../static/css/whatsapp.css">
    <link rel="stylesheet" href="../static/css/menssages.css">
    <script src="https://kit.fontawesome.com/79f542cb27.js" crossorigin="anonymous"></script>
    <title>Home</title>
</head>
<body>
    {% include './partial/navbar.html' %}
    {% include './partial/main_home_student.html' %}
    {% include './partial/footer.html' %}
    {% include './partial/whatsapp.html' %}
    <script src="../static/javascript/home_student.js"></script>
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
  ></script>
</body>
</html>

templates/layout_login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/menssages.css">
    <link rel="stylesheet" href="../static/css/login.css" />
    <title>Login</title>
  </head>
  <body>
    <div class="wrapper">
      {% include './partial/login.html' %} {% include './partial/_message.html'
      %}
    </div>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
  ></script>
  <script src="../static/javascript/login.js"></script>
</html>

templates/update_student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/css/crud_students.css">
    <link rel="stylesheet" href="../static/css/sidebar.css">
    <title>Actualizar Estudiante</title>
</head>
<body id="body">
    {% include './partial/sidebar.html' %}
    <div class="container crud-table" ng-app="myApp" ng-controller="namesCtrl">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Codigo Estudiantil</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Tipo de identificacion</th>
                    <th>Numero de identificacion</th>
                </tr>
            </thead>
            <tbody class="text-center">
                <tr>
                    <td>{{student.codigo_Student}}</td>
                    <td>{{student.name}}</td>
                    <td>{{student.lastname}}</td>
                    <td>{{student.TypeId.description}}</td>
                    <td>{{student.IDNumber}}</td>
                </tr>
            </tbody>
        </table>
        <div class="crude-form__wrapper" id="container" style="display:block">
            <h3 id="ed" style="display:block">Editar Estudiante</h3>
            <form action="/update_student/{{student.codigo_Student}}" autocomplete="off" method="POST" id="form" style="display:block">
                <div class="form-group"><label for="codigo_Student">Codigo Estudiantil</label><input class="form-control" id="codigo_Student" type="number" name="codigo_Student" required="required" value="{{student.codigo_Student}}" disabled />
                </div>
                <div class="form-group"><label for="name">Nombre</label><input class="form-control" id="name" type="text" name="name" required="required" value="{{student.name}}" />
                </div>
                <div class="form-group"><label for="lastname">Apellido</label><input class="form-control" id="lastname" type="text" name="lastname" required="required" value="{{student.lastname}}" />
                </div>
                <div class="form-group">
                    <label for="id_typeid">Tipo de identificacion</label>
                    <select name="id_typeid" class="form-control">
                        {% for type in typeids %}
                        <option value="{{type.id}}">{{type.description}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group"><label for="IDNumber">Numero de identificacion</label><input class="form-control id_number" id="IDNumber" type="number" name="IDNumber" required="required" value="{{student.IDNumber}}" />
                <button class="btn btn-primary">Editar</button>
                <button type="button" class="btn btn-primary" onclick="delet()"> Cancel</button>
            </form>
        </div>
    </div>
<script src="../static/javascript/update_student.js"></script>
<script src="https://kit.fontawesome.com/79f542cb27.js" crossorigin="anonymous"></script>
<script src="../static/javascript/sidebar.js"></script>
</body>
</html>