routes/Documents.py
import os
import webbrowser
import datetime
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from services.Documents import documentService
from services.TypeId import typeIdService
from services.States import stateService
from services.Administrativo import AdministrativeService
from werkzeug.utils import secure_filename

import index

Documents = Blueprint("documents", __name__)


@Documents.route("/upload", methods=["GET", "POST"])
def upload():
    if "code" in session:
        if session["type_of_user"] == 1:
            if request.method == "POST":
                codigo_Student = request.form["codigo_Student"]
                datetime_document = datetime.datetime.now()
                id_state = 1
                student_observation = request.form["observacion"]
                administrative_code = None
                administrative_observation = None
                file = request.files["file"]
                documents = documentService.get_document_cod_student(codigo_Student)
                if len(documents) == 0:
                    file.save(os.path.join(index.files, f"{codigo_Student} .pdf"))
                    documentService.create_document(
                        codigo_Student,
                        datetime_document,
                        id_state,
                        student_observation,
                        administrative_code,
                        administrative_observation,
                    )
                    documents = documentService.get_document_cod_student(codigo_Student)
                    for i in documents:
                        student = i.student
                    document = documents[0]
                    return render_template("home_student.html",student=student,document=document)
                elif len(documents) > 0 and documents[0].id_state == 2:
                    file.save(os.path.join(index.files, f"{codigo_Student} .pdf"))
                    documentService.create_document(
                        codigo_Student,
                        datetime_document,
                        id_state,
                        student_observation,
                        administrative_code,
                        administrative_observation,
                    )
                    documents = documentService.get_document_cod_student(codigo_Student)
                    for i in documents:
                        student = i.student
                    document= documents[0]
                    return render_template("home_student.html",student=student,document=document)
                else:
                    flash("El estudiante ya tiene un documento en proceso")
                    documents = documentService.get_document_cod_student(codigo_Student)
                    for i in documents:
                        student = i.student
                    document= documents[0]
                    return render_template("home_student.html",student=student,document=document)
            if request.method == "GET":
                return redirect(url_for("Estudiante.home_student"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))

#ruta para la previsualizacion del documento
@Documents.route("/preview/<id>", methods=["GET", "POST"])
def preview(id):
    if "code" in session:
        if session["type_of_user"] == 2:
            ruta = os.path.join(index.files, f"{id} .pdf")
            webbrowser.open(ruta)
            return redirect(url_for("Administrativo.home_administrativo"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))



#ruta para verificar documento por estudiante
@Documents.route("/verify/<id>", methods=["GET", "POST"])
def verify(id):
    if "code" in session:
        if session["type_of_user"] == 2:
            data = eval(id)
            documents = documentService().get_documents()
            document_by_student = documentService.get_document_cod_student(data[0])
            typeids = typeIdService().get_typeIds()
            administrative = AdministrativeService().get_administrative(data[1])
            states = stateService().get_states()
            return render_template('home_administrative.html', documents=documents, document_by_student=document_by_student[0], typeids=typeids,administrative=administrative,states=states)
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))

#ruta para actualizar estado del documento
@Documents.route("/update/<id>", methods=["POST"])
def update(id):
    if "code" in session:
        if session["type_of_user"] == 2:
            id = id
            document = documentService.get_document_id(id)

            if document:
                datetime_document = datetime.datetime.now()
                id_state = request.form["id_state"]
                administrative_code = request.form["administrative_code"]
                aministrative_observation = request.form["aministrative_observation"]

                documentService.update_document(
                    id,
                    datetime_document,
                    id_state,
                    administrative_code,
                    aministrative_observation,
                )
                return redirect(url_for("Administrativo.home_administrativo"))
            else:
                return redirect(url_for("Administrativo.home_administrativo"))
        else:
            return redirect(url_for("auths.index"))
    else:
        return redirect(url_for("auths.index"))

routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from services.Students import studentsService
from services.Administrativo import AdministrativeService


auths = Blueprint("auths", __name__)


@auths.route("/")
def index():
    return render_template("layout_login.html")


@auths.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        code = request.form["code"]
        IDNumber = request.form["IDNumber"]
        type_of_user = int(request.form["type_of_user"])
        session["code"] = code
        session["type_of_user"] = type_of_user

        if type_of_user == 1:
            student = studentsService().get_student(code)

            if student is None:
                flash(
                    "Usuario no encontrado por favor comuniquese con el administrador"
                )
                return redirect(url_for("auths.login"))
            elif student.IDNumber != IDNumber or student.codigo_Student != code:
                flash("Credenciales incorrectas")
                return redirect(url_for("auths.login"))
            else:
                return redirect(url_for("Estudiante.home_Student"))
        elif type_of_user == 2:
            administrative = AdministrativeService().get_administrative(code)

            if administrative is None:
                flash(
                    "Usuario no encontrado por favor comuniquese con el administrador de la pagina"
                )
                return redirect(url_for("auths.login"))
            elif administrative.IDNumber != IDNumber:
                flash("Credenciales incorrectas")
                return redirect(url_for("auths.login"))
            else:
                return redirect(
                    url_for(
                        "Administrativo.home_administrativo"
                    )
                )
    if request.method == "GET":
        return redirect(url_for("auths.index"))

@auths.route("/logout")
def logout():
    session.pop("code", None)
    return redirect(url_for("auths.login"))

templates/partial/_message.html
{% with messages = get_flashed_messages() %} {% if messages %} {% for message in
messages %}
<div class="alert alert-danger alert-dismissible fade show" role="alert" id="menssage">
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %} {% endwith %}

templates/partial/footer.html
<footer>
    <div class="waves">
        <div class="wave" id="wave1"></div>
        <div class="wave" id="wave2"></div>
        <div class="wave" id="wave3"></div>
        <div class="wave" id="wave4"></div>
    </div>
    <ul class="social_icon">
        <li><a href="#"><ion-icon name="logo-facebook"></ion-icon></a></li>
        <li><a href="#"><ion-icon name="logo-twitter"></ion-icon></a></li>
        <li><a href="#"><ion-icon name="logo-linkedin"></ion-icon></a></li>
        <li><a href="#"><ion-icon name="logo-instagram"></ion-icon></a></li>
    </ul>
    <ul class="menu">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Team</a></li>
        <li><a href="#">Contact</a></li>
    </ul>
    <p>&copy2022 RJD | All Rights Reserved</p>
</footer>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

templates/partial/login.html
<form action="/login" class="login" method="POST">
  <p class="title">Log in</p>
  <input type="number" required placeholder="Username" name="code" autofocus />
  <i class="fa fa-user"></i>
  <input type="password" required placeholder="Password" name="IDNumber" />
  <i class="fa fa-key"></i>
  <select name="type_of_user" class="input input-password">
    <option value="1">Estudiante</option>
    <option value="2">Administrativo</option>
  </select>
  <button>
    <i class="spinner"></i>
    <span class="state">Log in</span>
  </button>
</form>

templates/partial/main_home_adm.html
<div class="form-inline">
  <div class="form-group">
    <input class="form-control" type="text"  placeholder="Buscar:"  id="inputSearch" onkeyup="search()"/>
  </div>
</div>
<main>
    <div class="estado-documento">
        <table cellspacing="25" id="tablaDocument">
          <caption>ESTADO DE DOCUMENTO CARGADO</caption>
          <thead>
            <tr>
              <th>Fecha-Hora</th>
              <th>Codigo Estudiantil</th>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Estado</th>
              <th>Observacion Estudiante</th>
              <th>Observacion Administrativo</th>
              <th><i class="fa-solid fa-file-pdf"></i></th>
              <th><i class="fa-solid fa-pen-to-square"></i></th>
            </tr>
          </thead>
          <tbody>
            {% if administrative%}
            {% for document in documents %}
            <tr>
                <td>{{document.datetime_document}}</td>
                <td>{{document.codigo_Student}}</td>
                <td>{{document.student.name}}</td>
                <td>{{document.student.lastname}}</td>
                {% if document.id_state %}
                <td id="tdState">{{document.State.description}}</td>
                {% endif %}
                <td class="obs__esp">{{document.student_observation}}</td>
                {% if document.administrative_observation != None %}
                <td class="obs__esp">{{document.administrative_observation}}</td>
                {% else %}
                <td></td>
                {% endif %}
                <td><a href="{{url_for('documents.preview',id=document.codigo_Student)}}"><img src="../../static/icons/view-black.png" alt="Visualizar" class="pdf-visualize"></a></td>
                <td><a href="{{url_for('documents.verify',id=[document.codigo_Student,administrative.administrative_code])}}"><img src="../../static/icons/lapiz-black.png" alt="editar" class="img-edit"></a></td>
              </tr>
              {%endfor%}
              {%endif%}
          </tbody>
        </table>
      </div>
      {% if document_by_student %}
      <div class="filtro">
        <div class="edit-adm" id="revision">
          <form action="/update/{{document_by_student.id}}" autocomplete="off" method="POST" id="form">
            <div class="form-group">
              <label for="codigo_Student">Codigo Estudiantil</label
              ><input
                name="codigo_Student"
                class="form-control"
                id="codigo_Student"
                type="number"
                value="{{document_by_student.codigo_Student}}"
                disabled
              />
            </div>
            <div class="form-group">
              <label for="name">Nombre</label
              ><input
                class="form-control"
                id="name"
                type="text"
                name="name"
                value="{{document_by_student.student.name}}"
                disabled
              />
            </div>
            <div class="form-group">
              <label for="lastname">Apellido</label
              ><input
                class="form-control"
                id="lastname"
                type="text"
                name="lastname"
                value="{{document_by_student.student.lastname}}"
                disabled
              />
            </div>
            <div class="form-group">
              <label for="student_observation">Observacion Estudiante</label>
              <input
                class="form-control"
                id="student_observation"
                name="student_observation"
                value="{{document_by_student.student_observation}}"
                disabled
              ></input>
            </div>
            <div class="form-group">
              <label for="aministrative_observation"> Observation Aministrativo</label>
              <textarea
                class="form-control"
                id="aministrative_observation"
                name="aministrative_observation"
                required maxlength="100"
              ></textarea>
            </div>
            <div class="form-group">
              <label for="state">Estado</label>
              <select name="id_state" id="state" class="form-control" required>
                {% for state in states %}
                <option value="{{state.id}}">{{state.description}}</option>
                {% endfor %}
              </select>
            </div>
            <input
              type="hidden"
              name="administrative_code"
              value="{{administrative.administrative_code}}"
            />
            <button class="btn btn-primary" id="btn">Confirmar</button>
            <button type="button" class="btn btn-danger" onclick="cerrar()">Cancelar</button>
          </form>
        </div>
      </div>
      {% endif %}
    </div>
  </main>

templates/partial/main_home_student.html
<main class="main">
  <div class="contenedor-principal">
      <form action="/upload" class="container-instructions" method="POST" enctype="multipart/form-data">
        <h2>SUBIR DOCUMENTOS</h2>
        <div class="instructions">
          <p>Se debe adjuntar un solo archivo .PDF con los siguientes documentos:</p>
          <p>1. Certificado de afiliación a una EPS con fecha reciente.</p>
          <p>2. Comprobante de correspondiente a la Matricula finaciera</p>
          <p>3. Formato para la Matricula Asignaturas diligenciado</p>
          <p>
            <input type="hidden" name="codigo_Student" value={{student.codigo_Student}}>
            <input type="file" required name="file" id="file"  class="inputfile" accept=".pdf" onchange="ValidateSingleInput(this)"/>
          </p>
          <div>
            <p class="observation" maxlength="100">Observacion:</p>
            <textarea
              name="observacion"
              id="observacion"
              cols="30"
              rows="10"
              required maxlength="100"
            ></textarea>
          </div>
          <button class="ripple">
            Guardar
          </button>
        </div>
      </form>
  </div>
  {% include './partial/_message.html' %}
  <div class="estado-documento">
      <table cellspacing="25">
        <caption>ESTADO DE TU DOCUMENTO</caption>
        <thead>
          <tr>
            <th>Fecha-Hora</th>
            <th>Estado</th>
            <th>Observacion Estudiante</th>
            <th>id Administrativo</th>
            <th>Observacion Administrativo</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{{document.datetime_document}}</td>
            {% if document.id_state %}
            <td id="tdState">{{document.State.description}}</td>
            {% endif %}
            <td class="obs__esp">{{document.student_observation}}</td>
            {% if document.administrative_code != None %}
            <td class="obs__esp">{{document.administrative_code}}</td>
            {% endif %}
            {% if document.administrative_observation != None %}
            <td>{{document.administrative_observation}}</td>
            {% endif %}
          </tr>
        </tbody>
      </table>
  </div>
</main>

templates/partial/navbar.html
<header class="header">
   <nav class="nav">
    <div class="name">
      <p>Bienvenido {{student.name}} {{student.lastname}}</p>
    </div>
    <div class="logo-imagen">
      <img
        src="../../static/icons/COSMOS.png"
        alt="logo"
        class="logo"/>
    </div>
    <button class="nav-toggle" aria-label="Abrir menú">
      <i class="fas fa-bars"></i>
    </button>
    <ul class="nav-menu">
      <li class="nav-menu-item">
        <a
          href="../../static/recursos/Formato para Matricular Asignaturas.docx"
          download="Formato para Matricular Asignaturas.docx"
          class="nav-menu-link nav-link"
          >Formato</a
        >
      </li>
      <li class="nav-menu-item">
        <a href="" class="nav-menu-link nav-link">Manual</a></li>
      <li class="nav-menu-item">
        <a href="{{url_for('auths.logout')}}" class="nav-menu-link nav-link">Salir</a></li>
    </ul>
  </nav>
</header>

templates/partial/sidebar.html
<header id="header">
    <div class="icon_menu">
        <i class="fa-solid fa-bars" id="btn_open"></i>
    </div>
    <div class="logo_imagen">
        <img src="../../static/icons/COSMOS.png" alt="logo" class="logo"/>
    </div>
    <div class="nav">
        <ul class="nav-menu">
            <li class="nav-menu-item">
                <a href="{{url_for('auths.logout')}}" class="nav-menu-link nav-link">Salir</a>
            </li>
        </ul>
    </div>
</header>
<div class="menu__side" id="menu_side">
    <div class="name__page">
        <i class="fa-solid fa-user-check" title="Inicio"></i>
        <p>Bienvenido {{administrative.name}} {{administrative.lastname}}</p>
    </div>
    <div class="options__menu">
        <a href="{{url_for('Administrativo.home_administrativo')}}" class="selected">
            <div class="option">
                <i class="fa fa-home" title="Inicio"></i>
                <h4>Inicio</h4>
            </div>
        </a>
        <a href="{{url_for('Estudiante.crud_Student')}}">
            <div class="option">
                <i class="fa-solid fa-users" title="Estudiantes"></i>
                <h4>Estudiantes</h4>
            </div>
        </a>
        <a href="#">
            <div class="option">
                <i class="fa-solid fa-user-tie" title="Administrativos"></i>
                <h4>Administrativos</h4>
            </div>
        </a>
    </div>
</div>

templates/partial/whatsapp.html
<div class="whatsapp">
    <a href="https://wa.me/+573222492319?text=Necesito%20ayuda%20para%20subir%20el%20documento" target="_blank">
        <img src="../../static/icons/whatsapp.png"/>
    </a>
</div>